### ISSUE TITLE
アクセシブルなダイアログを知ろう

### ISSUE THREAD

**Issue by jp-knj** [monosus-bhsstt/learning-web-development#18]
# 課題

華やかなインタラクションを持つUIに興味が沸きますが
ぜひ、アクセシビルでユーザーに使われやすいUIにも目を向けるのも良いかもしれません！

英語の記事になりますが、綺麗なコーディング例にわかりやすい説明が載ってあります.
[おすすめの記事](https://tympanus.net/codrops/2021/10/06/how-to-implement-and-style-the-dialog-element/)

わかりやすい記事になります！ご参考に！
[おすすめの記事](https://code-kitchen.dev/html/)

**Comment by jp-knj** [comment]
通読したら、このコメントにスタンプください！

**Comment by mono-yano** [comment]
一通り読み終わりました！
確かに記事にあったように閉じるボタンがなかったり、ダイアログを閉じた後に元の場所に戻っていないとユーザーにとってはとても不便ですね。とてもわかりやすかったです！
ありがとうございます！

**Comment by jp-knj** [comment]
> 閉じるボタンがなかったり、ダイアログを閉じた後に元の場所に戻っていないとユーザーにとってはとても不便ですね。
UIをつくるのと同時にユーザの動作を考えれるようになったら、進歩できてるって捉えてください！

読んでくださり、ありがとうございます！
