### ISSUE TITLE
faq-collapse をアレンジを追加しよう

### ISSUE THREAD

**Issue by jp-knj** [monosus-bhsstt/learning-web-development#19]
# 課題

- [x] `divタグ` を `summary / detailタグ`に書き換えよう
- [x] CSS もタグ変更に伴って書き換えよう

こちらを参考にマークアップやスタイリングやふるまいを考えてみてください！
[参考記事](https://dequeuniversity.com/library/aria/expand-collapse-summary)

**Comment by mono-tmt** [comment]
@mono-yano
PR、確認しました！
LGTMだったので、クローズ
