### ISSUE TITLE
expanding cards にアレンジを追加

### ISSUE THREAD

**Issue by jp-knj** [monosus-bhsstt/learning-web-development#8]
# 課題
expanding cards にアレンジを追加しましょう

### 修正依頼内容
アレンジ後の動作になるように変更してください

`.css`ファイル
 - `h3` の `font-size`を`36px`に
 - `h3` の位置を上下左右中央に配置
 - クリック後にカードの画像に黒いオーバレイを追加

`.js`ファイル
 - `.forEach()`ではなく、`.map()`に書き換えてください

### クイズ内容
 - `.forEach()`と`.map()`の違いはなんでしょうか

### アレンジ後
[![Image from Gyazo](https://i.gyazo.com/c00999c3423426fd3d901172294863d6.gif)](https://gyazo.com/c00999c3423426fd3d901172294863d6)

### アレンジ前
[![Image from Gyazo](https://i.gyazo.com/f6b71fe49435cdb71ad0002bce75ccbf.gif)](https://gyazo.com/f6b71fe49435cdb71ad0002bce75ccbf)

**Comment by mono-yano** [comment]
.cssファイル
 - [x]  h3 の font-sizeを36pxに
→完了(2022/4/8)
- [x] h3 の位置を上下左右中央に配置
→完了(2022/4/8)
参考：https://www.w3.org/Style/Examples/007/center.ja.html
- [x] クリック後にカードの画像に黒いオーバレイを追加
→完了(2022/4/8)
参考：https://orange-log.com/overlay/

.jsファイル
- [x] .forEach()ではなく、.map()に書き換えてください
→取り組み中 (2022/4/8)
→完了(2022/4/12)

クイズ内容
.forEach()と.map()の違いはなんでしょうか
→forEachが配列に関数処理を実行するのみであるのに対して、mapは関数処理を実行して新しい配列を作り出すことができる。大量のWebページを作成するにあたって、元々の配列の中身を変更することは不具合の原因にもなる。そのため数パターンの配列に関数処理をする際は、forEachを複数制作したり配列の中身を変更したりするのではなく、mapを用いることが好ましい。

**Comment by mono-tmt** [comment]
@mono-yano LGTM です！
こちらの issue を Githubの commitメッセージでクローズしてみてください！
指定されたコミットメッセージくを push するだけで良いです！！

▼ 参考
https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#closing-multiple-issues
