### ISSUE TITLE
progress steps にアレンジ追加

### ISSUE THREAD

**Issue by jp-knj** [monosus-bhsstt/learning-web-development#9]
# 課題
progress steps にアレンジを追加しましょう

### 修正依頼内容
アレンジ後の動作になるように変更してください

`.css`ファイル
- 現状いる`circle`の`color`に`yellow`を追加

`.js`ファイル
 - `.forEach()`ではなく、`.map()`に置換
 - 不要な`console.log()`を削除
 - 重複したコードを削除するか、共通化してください

### クイズ内容
 - `console.log()`を削除する理由はなんでしょうか？
 - 重複したコードを共通化する理由はなんでしょうか？

### アレンジ後
[動画のリンク](https://i.gyazo.com/e246b0b9cf77e795cda5b66a2ab13c90.gif)

### アレンジ前
[動画のリンク](https://i.gyazo.com/424c0782fe330cf9501f3f582af38d1e.gif)

**Comment by mono-yano** [comment]
.cssファイル
- [ ] 現状いるcircleのcolorにyellowを追加
→cssのみ追加している状態...取り組み中(2022/4/8)

.jsファイル
- [x] .forEach()ではなく、.map()に置換
→取り組み中(2022/4/8)
→完了(2022/4/12)

- [x] 不要なconsole.log()を削除
→完了(2022/4/8)

- [x] 重複したコードを削除するか、共通化してください
→完了(2022/4/12)

クイズ内容

- console.log()を削除する理由はなんでしょうか？
・開発者のデバック用で公開しないようにするため。
・長期的な運用上、削除しないとコードが見にくくなるため。
・処理がされているので重くなるため？

- 重複したコードを共通化する理由はなんでしょうか？
・運用作業する上で、誰から見ても見やすくするため。
・省ける手間は省いた方が作業効率が上がるため。
・コードが少ない方がファイルが軽くなるため？

**Comment by mono-tmt** [comment]
@mono-yano 
LGTM です！
こちらの issue を Githubの commitメッセージでクローズしてみてください！

以下のリンクを参考にしてください
指定されたコミットメッセージを push するだけで良いです！！

▼ 参考
https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#closing-multiple-issues
